---
# MariaDB Ansible Role - Main Tasks

- name: Install MariaDB prerequisites
  ansible.builtin.apt:
    name:
      - software-properties-common
      - dirmngr
      - apt-transport-https
      - ca-certificates
      - python3-pymysql
    state: present
    update_cache: yes

- name: Add MariaDB APT repository key
  ansible.builtin.apt_key:
    url: "https://mariadb.org/mariadb_release_signing_key.asc"
    state: present

- name: Add MariaDB APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://mirror.netcologne.de/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: mariadb

- name: Install MariaDB server and client
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
      - mariadb-backup
    state: present
    update_cache: yes

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Check if root password is already set
  ansible.builtin.command: >
    mysql -u root -p'{{ mariadb_root_password }}' -e "SELECT 1"
  register: root_password_check
  failed_when: false
  changed_when: false
  no_log: true

- name: Set MariaDB root password (if not set)
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: yes
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  when: root_password_check.rc != 0
  no_log: true

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Create MariaDB configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0644'
  notify: restart mariadb

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: Create databases
  community.mysql.mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default(mariadb_character_set) }}"
    collation: "{{ item.collation | default(mariadb_collation) }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_databases }}"
  when: mariadb_databases | length > 0

- name: Create database users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    host: "{{ item.host | default('%') }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  loop: "{{ mariadb_users }}"
  when: mariadb_users | length > 0
  no_log: true

- name: Create backup directory
  ansible.builtin.file:
    path: "{{ mariadb_backup_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0750'
  when: mariadb_backup_enabled

- name: Setup backup cron job
  ansible.builtin.cron:
    name: "MariaDB backup"
    minute: "0"
    hour: "2"
    job: "/usr/bin/mariadb-dump --all-databases -u root -p'{{ mariadb_root_password }}' | gzip > {{ mariadb_backup_dir }}/backup-$(date +\\%Y\\%m\\%d-\\%H\\%M\\%S).sql.gz"
    user: root
    state: present
  when: mariadb_backup_enabled
  no_log: true

- name: Setup backup retention cleanup
  ansible.builtin.cron:
    name: "MariaDB backup cleanup"
    minute: "30"
    hour: "2"
    job: "find {{ mariadb_backup_dir }} -name 'backup-*.sql.gz' -mtime +{{ mariadb_backup_retention_days }} -delete"
    user: root
    state: present
  when: mariadb_backup_enabled

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
