---
minio_user: minio
minio_group: minio

minio_bin: /usr/local/bin/minio
minio_data_dir: /var/lib/minio
minio_env_file: /etc/default/minio

# optional defaults (nur als Fallback / f√ºr Templates)
minio_volumes: "/var/lib/minio"
minio_opts: "--address :9000 --console-address :9001"
